### ISSUE TITLE
kasutajavaade html 

### ISSUE THREAD

**Issue by Ann-JK** [KoppelSiim/library#8]
laenatud raamatud
tähtajad 
visuaalne indikaator
kuupäev

neile vaja eraldi db 

tagasta nupp (SQL delete from table)

**Comment by KoppelSiim** [comment]
Laenatud raamatud vaade lisatud

**Comment by KoppelSiim** [comment]
Kasutajavaade, lisasin funktsionaalsuse, et veeru tasutavärv muutub vastavalt hetke kuupäeva ja tähtaja vahele. Värvid on inline-css stiilis hetkel, lihtsalt testimise jaoks, kuid loogika töötab samamoodi. Vahede loogika : >= 7 - roheline bg, > 0 - kollane bg,<= 0 - punane (üle tähtaja), null või tühi string - hall, nii ilmselt ei tohiks juhtuda
